name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  #sdk: ">=2.1.0 <3.0.0"
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #cupertino_icons: ^0.1.2
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  flutter_hud: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
